### acessando via GET
GET http://localhost:3003/api/billingCycles
###
POST http://localhost:3003/api/billingCycles
//Content-Type: application/json

name: Janeiro/17
month: 1
year: 2017
credits[0][name]: Salario Empresa
credits[0][value]: 6500
credits[1][name]: Salario Professor
credits[1][value]: 2700
debits[0][name]: Telefone
debits[0][value]: 89.56
debits[0][status]:PAID
debits[1][name]: Carro
debits[1][value]: 255
debits[1][status]:SCHEDULED
###
PUT http://localhost:3003/api/billingCycles
Content-Type: application/json

{  
      "code_user": 1,
      "code_relation": 101031056107335,
      "input": "Não",
      "output": "Respeito sua opinião. Mas fique atento por que estes sistemas podem ser muito úteis"
}
###
DELETE http://localhost:3003/api/billingCycles
Content-Type: application/json
{
  "code_current": 101030852859994,
}
###
PATCH  http://localhost:3003/api/billingCycles
Content-Type: application/json

{
  "userChannel": "wtc"
}
###